name: christian_songs_zaboor_v2
description: Christian Songs and Zaboor app - Urdu/English.
publish_to: "none"
version: 2.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
